FROM python:3.9

# Set the working directory to /app
WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy the rest of the application code into the container
COPY ./app.py /code/

EXPOSE 7860

# Start the Gradio app
CMD ["python", "/code/app.py"]